# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 932656d972d95d0a9df1efd46079d0e8b01ac1155dac96a95c1c618527d734bb1c9435195294ac554b7591402678a339d2cd23b94e274b1d2419bd2281c6d88c

test:
  secret_key_base: f200f145433a75a3ba3472cec4ca7f0e7f23ae83d0d5f80ee0b8140c2bbf12bf17a4586eb705b6b51c519a71c345833f56f576f4bf75049a8a85ea1c35d0fe9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
